### ISSUE TITLE
ドラッグ＆ドロップで画像がアップロードされない方法がある

### ISSUE THREAD

**Issue by masakah** [movabletype/mt-plugin-MTBlockEditor#1]
![aa](https://user-images.githubusercontent.com/6838696/115486630-05227000-a292-11eb-9706-f5890f1730e1.jpg)
画像のモーダルウィンドウにドラッグ＆ドロップの場合はうまくいきますが、エディタ内のブロックを追加などにドラッグ＆ドロップした場合にモーダルは開くが画像がアップロードされません。

**Comment by usualoma** [comment]
@masakah 
https://github.com/movabletype/mt-plugin-MTBlockEditor/releases/tag/v0.0.12-alpha で修正されました。
確認お願いします。
