### ISSUE TITLE
エラーで全く動かないのですが……

### ISSUE THREAD

**Issue by yupyom** [movabletype/mt-plugin-MTBlockEditor#24]
新規でMT 7 (r.4902)ソフトウェア版を入れて、MTBlockEditorを入れてみたのですが、全く動きません。

データベースのアップデートをしようとして、以下のエラー。
Can't use an undefined value as a HASH reference at /_path_to_mt_/cgi-bin/mt/extlib/Data/ObjectDriver/BaseObject.pm line 308.

デバッグモードでログを出すと以下のような結果に。
Request completed in 0.132 seconds.
Bareword found where operator expected at /_path_to_mt_/plugins/MTBlockEditor/lib/MT/Plugin/MTBlockEditor/Block.pm line 102, near "s/-/_/gr"
Bareword found where operator expected at /_path_to_mt_/plugins/MTBlockEditor/lib/MT/Plugin/MTBlockEditor/Block.pm line 111, near "s/-/_/gr"

となります。プラグインを外すと元には戻ります。

![2021-07-21_01h35_29](https://user-images.githubusercontent.com/306949/126365988-ba90b9a5-4b88-4592-9ce4-f88e92b38403.png)

**Comment by usualoma** [comment]
詳細な報告ありがとうございます。大変助かります。

確認したところ、Perlの5.14未満で動作しない状態であることを確認しました。CentOS 6などで利用するとご報告をいただいたような内容でエラーがでるものと思います。
以下の課題として修正予定です。修正版のリリースができましたらご連絡します。

https://movabletype.atlassian.net/browse/MTC-28028

よろしくお願いします。

**Comment by yupyom** [comment]
ご対応ありがとうございます。
まさに、Perl 5.10.1の環境でした。確認したところ、クライアントが利用している国内のホスティングサービス（マネージド型サーバー）のOS環境が、CentOS6をベースに、独自でバックポートで保守しているところがいくつかあり、まだまだ古いPerl環境を使用せざるを得ないところが残っているようです。

なお、この話とは関係ないですが、当該サーバーではHTML::Entitiesも入っていなかったり、CPANも使えなかったりするので、素のMT7自体が動かなかったのですが、ローカルでとってきたHTML::Entitiesをextlibに追加してなんとか動かすようにしています……。（MT7は色々とハードルが高いように感じています）

**Comment by usualoma** [comment]
@yupyom 
5.10.1 でも動作するように修正した 1.0.8 をリリースしました。こちらであれば動作するかと思います。
https://github.com/movabletype/mt-plugin-MTBlockEditor/releases/tag/v1.0.8

確かに「OSがあって、できることはファイルのアップロードだけ」というような環境だと、ご指摘の通り難しいことがあるかもしれないですね。参考にさせていただきます。

**Comment by yupyom** [comment]
迅速なご対応ありがとうございました！
試してみまして、アップデートがうまく進み、また、いくつかのカスタムブロックタイプを追加してみて、無事に動作することを確認できました。
クローズとしていただいて大丈夫かと思います。

**Comment by yupyom** [comment]
というか、解決したので、クローズしました。
