### ISSUE TITLE
プラグインtextcolorの初期化に失敗しました

### ISSUE THREAD

**Issue by AidmaNarita** [movabletype/mt-plugin-MTBlockEditor#29]
テキストの場合、input にフォーカスするたびに「プラグインtextcolorの初期化に失敗しました」と表示されます。
そのまま使用して、文字色の変更などは出来るのですが、警告が出るので邪魔になります。
関連プラグインの不足でしょうか。
![image](https://user-images.githubusercontent.com/76584818/137896834-699640fe-ae04-425b-ae11-4efcda15b54c.png)

**Comment by usualoma** [comment]
@AidmaNarita ご報告ありがとうございます。
以下の情報について教えていただけますでしょうか。

* MTのバージョン情報
* OSとウェブブラウザの種類とバージョン情報

またもし可能であれば、ブラウザの開発者コンソールを開いた状態でエラーが発生した場合に以下のような情報が表示されると思いますので、こちらの情報を教えていただけますでしょうか。

![記事の作成_-_MTBlockEditor___Movable_Type](https://user-images.githubusercontent.com/30598/138041495-ac3b66ca-a210-406f-9ca5-ea3d344b0d23.jpg)

よろしくお願いいたします。

**Comment by AidmaNarita** [comment]
その後、MTとブロックエディタを最新版に更新した所、「TinyMCE5」でブロックエディタが動作しなくなりました。
現在はMTに同梱されている「TinyMCE 1.41」を使用する様にして、しのいでおります。

現在利用中のそれぞれのバージョンは以下の通りです。
Movable Type Pro r.5301 with: Professional Pack 3.08
MTBlockEditor 1.1.7

開発環境と本番環境が有り、開発環境では問題なく動いております。
問題が発生している本番環境は、WEBサーバーから外部への発信は許可されていない（外部からのHTTPSアクセスに対するレスポンスのみ）ので、なにかしらJSが外部リソースを利用しようとして失敗しているのではないかと邪推しておりますが、原因が特定出来ず困っております。

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/76584818/190155034-5b95c942-46be-4d87-a899-5e5b773de2a5.png">

原因と解決について、なにかおわかりになられますでしょうか。

**Comment by usualoma** [comment]
@AidmaNarita 返信が滞っており申し訳ありませんでした。
開発環境では動作されているとのことで、その点については安心しました。

いただいたスクリーンショットから判断しますと、エラーが scheduler.production.min.js の中で発生しているようなのですが、こちらはプラグインなどによる拡張でしょうか。通常 `console.warn` が `is not a function` になることはないので、ここから想像できるのは、 scheduler.production.min.js などで、 `window.console` を上書きしたりしているという可能性かと思います。

scheduler.production.min.js を無効化できるようであれば、無効化した状態でもMTBlockEditorの利用でエラーが出るかどうか、確認していただいてもよいでしょうか。

**Comment by AidmaNarita** [comment]
@usualoma ご回答有難うございました。
scheduler.production.min.js はChromeのツールで確認すると 「mt-block-editor.js からのメッセージ」と出ますが、別のプラグインの影響と言う事でしょうか。
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/76584818/190319009-a40814fb-3800-4f66-8a21-081ca5ab354a.png">

プログラムやMTの構造についてあまり知識がなくて申し訳ございませんが、「scheduler.production.min.js 」はファイルとして読み込んでおらず、以下の mt.cgi を経由して webpack として配信されている模様で、無効化にする方法がわかりません。
https://foo-bar.jp/cgi-bin/mt.cgi?__mode=view&_type=entry&blog_id=21 

また、Chromeのツールで「scheduler.production.min.js 」の「リンクのアドレスをコピー」すると、以下のアドレスになります。
webpack:///node_modules/scheduler/cjs/scheduler.production.min.js

![image](https://user-images.githubusercontent.com/76584818/190319382-0f17e48c-8dd5-4850-bbce-e268bdd17915.png)

こちらで解る範囲の情報を記載してみましたが、解決の糸口になりますでしょうか…。

**Comment by usualoma** [comment]
@AidmaNarita すみません、 `scheduler.production.min.js` については私の勘違いで、ご指摘の通り MTBlockEditor に含まれるファイルでした。 `scheduler.production.min.js` を除外することはできません。

ただやはり、 `console.warn is not a function` となるという状態はMTでは通常は発生せず、開発環境では問題なく動いているという状況から判断しても、
* Movable Type のサードパーティ制プラグイン
    * もしくはプラグイン内の設定
* Google Chrome の拡張機能

のどれかの作用により、 `window.console` に変更が加えられて `console.warn is not a function` となるような状態になっていると考えています。

現象の切り分けとしては、基本的にはサードパーティ制プラグインなどを無効にして、試していただく形になると思います。


ただ、MTBlockEditorの次のバージョンでは、上記の箇所で `console.warn` が呼ばれることがなくなる予定のため、次のバージョンではエラーが発生しにくいものとなるとは考えています。

よろしくお願いいたします。

**Comment by AidmaNarita** [comment]
@usualoma 以下のプラグインが干渉していた模様で、オフにした所正常に動作する様になりました。
https://plugins.movabletype.jp/juxtaposition/imageuploadutility.html
※ライセンスの関係で、開発環境には入れておりませんでした。
こちらのプラグインはそれほど使用していないので、オフの状態で運用する様にいたします。
ご助言有難うございました。

**Comment by usualoma** [comment]
解決されたとのことで何よりです。
ありがとうございました。
