### ISSUE TITLE
増減するliタグをulタグで囲みたい

### ISSUE THREAD

**Issue by rfv-zz** [movabletype/mt-plugin-MTBlockEditor#31]
よくあるul > li タグのブロックを作成するとしてこのliタグは増減するブロックと作成した場合に、現状親ブロック側でulとして囲む処理をカスタムスクリプトで記載しても動作しませんでした。

- ul ブロック: ブロック追加を許可し、liを囲む処理をカスタムスクリプトに記載しておく
- li ブロック: ulブロック側に追加するブロック

現状ulブロック側でliブロックをwrapするような処理は仕様として出来ない、という認識でよいでしょうか？

コーディング側がブロックを意図してコーディングしない事のほうが多いので、大部分はul > li タグで実装されてる事が多いです。
そのために現状仕様で不可となると全てdivタグとして書き直していただく必要があります。

もし解決方法があれば教えていただきたいです。

**Comment by usualoma** [comment]
@rfv-zz 回答遅くなりすみません。

こちらの記事（ご質問を拝見してから用意したものですが）が、MovableType.net のものですが、ソフトウェア版のプラグインでも同様に利用できます。
こういった方法で解決が可能かどうか、一度ご確認いただけけますでしょうか。
https://movabletype.net/blog/2021/12/ul-li.html

よろしくお願いします。

**Comment by rfv-zz** [comment]
@usualoma 

ありがとうございます！
上記のブロックで試してみます。
ありがとうございました。
