### ISSUE TITLE
「プリセット」内の「ブロックの表示設定」と「カスタムブロック」内の「ブロックの追加設定」に新規追加したブロックが自動的に追加される。

### ISSUE THREAD

**Issue by imark-lab** [movabletype/mt-plugin-MTBlockEditor#36]
「プリセット」内の「ブロックの表示設定」と「カスタムブロック」内の「ブロックの追加設定」に新規追加したブロックが自動的に追加されます。

そのためプリセットやカスタムブロックであらかじめ表示するブロックを限定していても後からブロックを追加するとそれらが表示されるようになってしまいます。（画像はプリセット作成後に新規ブロックを追加した際のプリセットのブロックの表示設定部分です。）
![image](https://user-images.githubusercontent.com/64005250/172768107-1ea472eb-554c-4f32-8ee0-22119cb4c10d.png)

**Comment by usualoma** [comment]
フィードバックありがとうございます。
現在リリースされているバージョンでは、自動で追加されるのが仕様となっております。

ただ「自動で追加されないで欲しい」という同様の声も複数いただいていますので、将来のリリースで改善できるように現在調整中です。すみませんが今しばらくお待ちいただけますでしょうか。

よろしくお願いいたします。

**Comment by imark-lab** [comment]
仕様とのこと承知しました。ご教授いただきありがとうございます。
将来のリリース大変楽しみにしております。

早速のご返信ありがとうございました。閉じさせていただきます。
