### ISSUE TITLE
ブロックを入れ子にした際に、入れ子になっているブロックでカスタムスクリプトが動かないことが稀にある。

### ISSUE THREAD

**Issue by imark-lab** [movabletype/mt-plugin-MTBlockEditor#40]
[使用バージョン]
v1.1.4

ブロックを入れ子にした際に内部のブロックのカスタムスクリプが動かず、そのままの状態で出力されることが稀にあります。
起こるタイミングはランダムなのですが、階層が深いブロックや入れ子の要素数が多いブロックにおいて起こる確度が高い傾向にあるように思います。

例えばリストブロックという親ブロック（仮称）の中にリストテキストという子ブロック（仮称）を追加すると、
稀に内部のリストテキストのカスタムスクリプトが動かずにそのまま出力されてしまうことがあります。プレビューの状態のままページ出力されるため管理画面で崩れている場合はそのままページが出力されてしまう状態になっています。

[正しく出力されている状態]
![スクリーンショット 2022-08-12 15 23 28](https://user-images.githubusercontent.com/64005250/184297331-ef71c761-233c-492c-98c3-57a688be1562.png)

[カスタムスクリプトが動いていない状態]
![スクリーンショット 2022-08-12 15 23 09](https://user-images.githubusercontent.com/64005250/184297402-6b87fa72-571b-4d08-a350-c3419513d582.png)

**Comment by usualoma** [comment]
@imark-lab 
ご報告ありがとうございます。
v1.1.5 で、カスタムブロックの表示の最適化と調整が行われたため、上記のような問題が発生しにくくなっています。
お手数をおかけしますが最新版の v1.1.6 で問題が解消されるかどうか、ご確認をいただけますでしょうか。
よろしくお願いします。

**Comment by imark-lab** [comment]
早速のご返答誠にありがとうございます。
こちらアップデートした上で同様の現象が発生するか検証してみます。

**Comment by imark-lab** [comment]
こちらバージョンアップした上で確認させていただいたところ、
バグが発生する確度は確かに低くなったようには思うのですが入れ子のブロックを増やしてプレビューの表示非表示を繰り返すなど、高負荷の作業を繰り返すと稀にご報告させていただいた現状が起こってしまう状況になっています。

恐らく小ブロックのレンダリングが全て終了する前に親ブロックのカスタムブロックが読み込まれてしまっているのですが、再現率が100%でないのでカスタムスクリプト側での対策が難しいかと思い悩んでいる次第です。

**Comment by usualoma** [comment]
@imark-lab 確認ありがとうございます。お手数をおかけしてすみません。

カスタムブロックからは、一般的には「常に `MTBlockEditorSetCompiledHtml` が呼ばれる保証」というものがないために、エディタ側で処理のタイムアウトを設定しているのですが、ご連絡いただいた内容からするとそのタイムアウトにかかってしまっているものと思います。

この問題については、次回以降のリリースで、子ブロック数に応じてタイムアウトを伸ばすなどの形で対応を検討したいと考えています。

またタイムアウトの値を変更する正式なAPIは提供していないのですが、現在のバージョンではプラグインを使って変更することが可能です。以下のプラグインをインストールすると、タイムアウトが現在の2秒から10秒に変更されます。
https://github.com/usualoma/mt-plugin-mtbe-ExtendCompileTimeout/releases/tag/v0.0.1

タイムアウトはこのファイルの7行目で設定しているので、この値を変えていただければ変更することができます。
https://github.com/usualoma/mt-plugin-mtbe-ExtendCompileTimeout/blob/main/plugins/ExtendCompileTimeout/tmpl/extension.tmpl

このプラグインについてはシックスアパートの提供する公式なものではないので、動作の保証はできないのですが、問題がタイムアウトである場合には、MTBlockEditor 側で対応されるまでの間の回避策としては利用可能であると思います。

**Comment by imark-lab** [comment]
@usualoma 
早速のご返信ありがとうございます。
タイムアウトの問題とのこと承知しました。
プラグインについてもご教授いただきありがとうございます。

MTBlockEditor側での対応を待ってから導入を検討しようと思います。
ありがとうございました。
