### ISSUE TITLE
プレビュー機能をオフにしてブロックを追加していくとパフォーマンスが著しく低下する

### ISSUE THREAD

**Issue by imark-lab** [movabletype/mt-plugin-MTBlockEditor#41]
プレビュー機能をオフにしたカスタムブロックを追加していくとカスタムブロックの数に伴ってパフォーマンスが低下していき、最終的にブロックの追加に30秒ほどかかるようになります（ブロックを増やしていけばさらに遅くなっていくかと考えられます。）
オンクリックイベント全てでこの現象が見られるようです。

mt-block-editor.jsでquerySelectorAllの実行時間にとても時間がかかっているのでおそらくこのあたりでオンクリックの度にカスタムブロック全てが参照され、カスタムブロックの増加に伴って実行時間が長くなるのではないかと想像しています。

![image](https://user-images.githubusercontent.com/64005250/188767370-09480638-bc77-412e-8e20-931abe5f0a68.png)

こちら側での対策があれば検討したいのですがむずかしそうでしょうか。

**Comment by usualoma** [comment]
@imark-lab 詳細なご報告ありがとうございます。

スクリーンショットから、 1.1.4 をインストールしていただいていると仮定してご回答いたします。

querySelectorAll の実行回数に関しては、 1.1.7 で改善されていますので、アップデートしていただくことで改善される可能性があると思います。

またプレビューを無効にした場合の挙動につきましては、 #40 と同様の問題でもありますが、次のリリースで大きく改善される予定です。
また、お問い合わせの件の問題の解消に直接つながるかどうか確実ではないものの、今回ご指摘の内容から改善できる点が見つかったため、次のリリースではその点に関する改善も含まれる予定です。

本件については、利用者側での回避策はありません。
よろしくお願いいたします。

**Comment by imark-lab** [comment]
@usualoma 

毎度早速のご返信を誠にありがとうございます。
1.17では改善され、次回リリースの検討していただけるとのことありがとうございます。

**Comment by usualoma** [comment]
@imark-lab 
おまたせしてすみませんでした。
情報のご提供などありがとうございました。
#40 の方も含めて改善の対応を行った 1.1.8 をリリースしましたので、よろしければお試しいただければ幸いです。
https://github.com/movabletype/mt-plugin-MTBlockEditor/releases/tag/v1.1.8
よろしくお願いします。

**Comment by imark-lab** [comment]
@usualoma 
本件ご連絡が遅くなりました。

詳しい検証は行っていないものの、v 1.1.8 以降から著しくパフォーマンスが低下することは無くなりました。
#40 の件に関しても同様にJSで描画した際の不具合は今の所確認されていません。
ありがとうございました。
