### ISSUE TITLE
サイトをインポートした際に「編集した内容をDIV要素で囲む」に自動でチェックが入る

### ISSUE THREAD

**Issue by imark-lab** [movabletype/mt-plugin-MTBlockEditor#45]
システム > ツール > サイトのエクスポートからエクスポートしたデータを異なる環境にインストールされたMT7でインポートした際に、全てのカスタムブロックの「編集した内容をDIV要素で囲む」の項目に自動でチェックが入る事象が確認されました。

▼移行元のバージョン
Movable Type Pro：r.5402
MTBlockEditor：1.1.9

▼移行先のバージョン
Movable Type Pro：r.5402
MTBlockEditor：1.1.9

<img width="375" alt="スクリーンショット 2023-03-08 14 24 54" src="https://user-images.githubusercontent.com/64005250/223626799-88ec8d86-037e-4d5e-879e-ec62f7bd7af3.png">

**Comment by usualoma** [comment]
@imark-lab 返信遅くなり申し訳ありません。フィードバックありがとうございます。
不具合と思われますので、確認後に修正します。

**Comment by usualoma** [comment]
@imark-lab 大変お時間をいただいてしまいましたが、こちらの件については本日リリースの 1.2.0 で修正されています。

https://github.com/movabletype/mt-plugin-MTBlockEditor/releases/tag/v1.2.0
