### ISSUE TITLE
マルチドメイン環境での画像ブロックのパスが、ログイン時のドメインで挿入されてしまう。

### ISSUE THREAD

**Issue by okoshi-evoworx** [movabletype/mt-plugin-MTBlockEditor#46]
マルチドメイン環境で管理画面へのログインURLが複数ある場合、画像ブロックで追加した画像のパスがログイン時のドメインで挿入されてしまう。

### 【例】
https://example.com/mt/admin
でログインして、画像ブロックで画像を挿入すると
https://example.com/uploads/hoge.jpg
として埋め込まれる。こちらが意図した挙動です。

MTクラウドで提供される初期ドメイン、
https://xxx.movabletype.biz/mt/admin
でログインして同様の操作をした場合、
https://example.com/ のサイト内のアセットであっても
https://xxx.movabletype.biz/uploads/hoge.jpg として埋め込まれてしまう。
※画像アップロード時や、画像選択時はiframeで表示されているのでこのときはサムネイルの表示ができています。

また、同じ契約で
https://subdomain.example.com というサイトをマルチドメインで管理していた場合
https://subdomain.example.com/mt/admin でもログインできますが、
こちらのURLでログインした状態で https://example.com/  のコンテンツを編集すると、
https://subdomain.example.com/uploads/hoge.jpg として埋め込まれプレビューなどができなくなってしまいます。

編集時に該当のドメインからログインするといった運用面でカバーするしか方法はないのでしょうか？

**Comment by usualoma** [comment]
@okoshi-evoworx フィードバックありがとうございます。
手元のMTクラウドの環境で症状が再現できなかったため、いくつか確認させてください。

* 編集中のドメインに置き換わってしまう症状は、画像ブロックに画像を挿入してすぐに発生しますでしょうか、あるいは「保存」や「保存したデータの編集」などを経た後に発生しますでしょうか
* 画像のパスを相対パスに変換するようなプラグインはインストールされていますでしょうか。

よろしくお願いします。

**Comment by okoshi-evoworx** [comment]
@usualoma 
ご回答ありがとうございます。

> 編集中のドメインに置き換わってしまう症状は、画像ブロックに画像を挿入してすぐに発生しますでしょうか、あるいは「保存」や「保存したデータの編集」などを経た後に発生しますでしょうか
画像ブロック挿入後すぐに発生し、保存後も継続したままになります。

> 画像のパスを相対パスに変換するようなプラグインはインストールされていますでしょうか。
[AssetRelativePath](https://plugins.movabletype.jp/authorf6b1b/assetrelativepath.html)を入れたままになっていたので 無効にして試してみたいと思います。

よろしくお願いします。

**Comment by okoshi-evoworx** [comment]
@usualoma 
AssetRelativePathを無効にしたところ問題なく動作するようになりました。

ご対応いただきありがとうございました。
